[package]
name = "ferrischat_snowflake_generator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
time-safety-checks = []
default = ["time-safety-checks"]

[dependencies]
